### ISSUE TITLE
Datasets directory 

### ISSUE THREAD

**Issue by aswa123** [hu64/CenterPoly#1]
Hello Sir,
Thank you for your wok.
can you please give more detailed about the requirements and the data directory.

**Comment by hu64** [comment]
Hi, the datasets are expected to be in "/store/datasets/DATASET_NAME". If you want to use another path, you can change it in the code, I suggest you use a search function to find to places to change it in the code. Concerning the requirements, if you are having trouble installing the code, I suggest you use this guide from the original CenterNet repo (https://github.com/xingyizhou/CenterNet/blob/master/readme/INSTALL.md). I am running pytorch 1.4.0 and cuda 10.0.
